skip-commit-generation-prompt = true
[projects."github.com/fcmiranda/matchmaker"]
worktree-path = "{{ repo_path }}/../{{ branch | sanitize }}"

[projects."github.com/fcmiranda/lazygitrs"]
worktree-path = "{{ repo_path }}/../{{ branch | sanitize }}"
