[tui]
percentage = 45
min = 5
max = 20

[preview]
show = true
wrap = true

[start]
command = 'fd --hidden --type f --type d --exclude .git'

[[preview.layout]]
command = 'eza -T --icons --color=always --level=2 {}'
side = 'right'
percentage = 100
min = 120

[results]
scroll_wrap = true
wrap = false
autoscroll.end = true
autoscroll.context = 0
reverse = false

[matcher]
sort_threshold = 0

[exit]
abort_empty = true
