[tui]
percentage = 45
min = 5
max = 20

[preview]
show = true
wrap = true
border.title_fg = 'cyan'


[start]
command = 'fd --hidden --type f --type d --exclude .git'

[query]
prompt_style.fg = 'cyan'

[[preview.layout]]
command = 'if [ -d {} ]; then eza -T --icons --color=always --level=2 {}; else bat --style=numbers --color=always --line-range=:300 {}; fi'
side = 'right'
percentage = 80

[results]
scroll_wrap = true
wrap = false
autoscroll.end = true
autoscroll.context = 0
reverse = false

[matcher]
sort_threshold = 0

[exit]
abort_empty = true
