# Omarchy-generated acpd configuration
# Auto-generated by omarchy-theme-set — do not edit manually.
# Template: ~/.dotfiles/main/acpd/.config/omarchy/themed/acpd.toml.tpl

listen_addr = "127.0.0.1"
port = 4040
pid_file = "/tmp/acpd.pid"
shutdown_timeout_secs = 30
log_level = "info"

[theme]
active_spinner = "minidot"

[theme.states.idle]
icon = "󱥂"
color = "{{ color14 }}"

[theme.states.busy]
icon = "󰑮"
color = "{{ color11 }}"

[theme.states.working]
icon = "󰑮"
color = "{{ color11 }}"

[theme.states.question]
icon = "󱜻"
color = "{{ color13 }}"

[theme.states.permission]
icon = "󱅭"
color = "{{ color1 }}"

[theme.states.error]
icon = "󰨄"
color = "{{ color1 }}"

[spinners]
minidot = { interval = 83, frames = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"] }
line = { interval = 100, frames = ["|", "/", "-", "\\"] }
jump = { interval = 100, frames = ["⢄", "⢂", "⢁", "⡁", "⡈", "⡐", "⡠"] }
pulse = { interval = 125, frames = ["█", "▓", "▒", "░"] }
points = { interval = 143, frames = ["∙∙∙", "●∙∙", "∙●∙", "∙∙●"] }
meter = { interval = 143, frames = ["▱▱▱", "▰▱▱", "▰▰▱", "▰▰▰", "▰▰▱", "▰▱▱", "▱▱▱"] }
hamburger = { interval = 333, frames = ["☱", "☲", "☴", "☲"] }
ellipsis = { interval = 333, frames = ["·", "..", "...", ".."] }
globe = { interval = 250, frames = ["🌍", "🌎", "🌏"] }
moon = { interval = 125, frames = ["🌑", "🌒", "🌓", "🌔", "🌕", "🌖", "🌗", "🌘"] }
monkey = { interval = 333, frames = ["🙈", "🙉", "🙊"] }
arc = { interval = 150, frames = ["◜", "◠", "◝", "◞", "◡", "◟"] }
nerd = { interval = 100, frames = [" ", " ", " ", " "] }
nerdarc = { interval = 120, frames = ["◜", " ", "◝", "◞", "◡", "◟", " "] }
dot = { interval = 100, frames = ["⣾", "⣽", "⣻", "⢿", "⡿", "⣟", "⣯", "⣷"] }
