# Omarchy-generated tmux color variables
# Auto-generated by omarchy-theme-set — do not edit manually.
# Template: ~/.config/omarchy/themed/tmux-colors.conf.tpl

set-environment -g CURRENT_COLOR "{{ color14 }}"
set-environment -g PREFIX_COLOR "{{ color13 }}"
set-environment -g SESSION_COLOR "{{ color4 }}"
set-environment -g SESSION_ACTIVE_FG "{{ background }}"
set-environment -g HOST_COLOR "{{ color4 }}"
set-environment -g ACTIVE_BORDER_COLOR "{{ color4 }}"
set-environment -g MESSAGE_COLOR "{{ color3 }}"
set-environment -g SEGMENT_BG "{{ color8 }}"
set-environment -g FG "{{ foreground }}"