# Omarchy-generated tmux color variables
# Auto-generated by omarchy-theme-set — do not edit manually.
# Template: ~/.config/omarchy/themed/tmux-colors.conf.tpl

CURRENT_COLOR="{{ color14 }}"
PREFIX_COLOR="{{ color13 }}"
SESSION_COLOR="{{ color4 }}"
HOST_COLOR="{{ color4 }}"
ACTIVE_BORDER_COLOR="{{ color4 }}"
MESSAGE_COLOR="{{ color3 }}"
SEGMENT_BG="{{ color8 }}"
FG="{{ foreground }}"