# Omarchy-generated tmux color config
# Auto-generated by omarchy-theme-set — do not edit manually.
# Template: ~/.config/omarchy/themed/tmux-colors.conf.tpl

# Direct style settings (no variable expansion — reliable on fresh tmux start)
set -g message-command-style "bg=default,fg={{ color3 }}"
set -g message-style "bg=default,fg={{ color3 }}"
set -g mode-style "bg=default,fg={{ color3 }}"
set -g status-style "bg=default,fg={{ foreground }}"
set -g pane-border-style "fg={{ color8 }},bg=default"

# User options for #{@VAR} references in format strings
set -g @CURRENT_COLOR "{{ color14 }}"
set -g @PREFIX_COLOR "{{ color13 }}"
set -g @SESSION_COLOR "{{ color4 }}"
set -g @SESSION_ACTIVE_FG "{{ background }}"
set -g @HOST_COLOR "{{ color4 }}"
set -g @ACTIVE_BORDER_COLOR "{{ color4 }}"
set -g @SEGMENT_BG "{{ color8 }}"
set -g @FG "{{ foreground }}"
set -g @ACCENT_COLOR "{{ accent }}"
set -g @POPUP_BORDER_COLOR "{{ accent }}"
set -g @POPUP_TEXT_COLOR "{{ color14 }}"