"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_os)\
$os\
[ ](fg:color_os)\
[](color_dir)\
$directory\
[ ](fg:color_dir)\
[](color_git)\
$git_branch\
$git_status\
[ ](fg:color_git)\
[](color_lang)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$custom\
[](fg:color_lang)\
$line_break\
$character"""

palette = 'omarchy_theme'

[palettes.omarchy_theme]
color_bg = '#2e3440'
color_text = '#eceff4'
color_comment = '#4c566a'
color_os = '#434c5e'
color_dir = '#88c0d0'
color_git = '#8fbcbb'
color_lang = '#a3be8c'
color_vim_insert = '#a3be8c'
color_vim_normal = '#81a1c1'
color_vim_visual = '#b48ead'

[os]
disabled = false
style = "bg:color_os fg:color_text"
format = '[ ❄ ]($style)'

[username]
show_always = true
style_user = "bg:color_lang fg:color_bg"
style_root = "bg:color_lang fg:color_os"
format = '[ $user ]($style)'

[directory]
style = "fg:color_bg bg:color_dir"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = "󰋩 "
"Developer" = "󰲋 "

[git_branch]
symbol = " "
style = "fg:color_bg bg:color_git"
format = '[[ $symbol$branch ]($style)]($style)'

[git_status]
style = "fg:color_bg bg:color_git"
format = '[[($all_status$ahead_behind )]($style)]($style)'

[nodejs]
symbol = " "
style = "fg:color_bg bg:color_lang"
format = '[[ $symbol( $version) ]($style)]($style)'

[rust]
symbol = " "
style = "fg:color_bg bg:color_lang"
format = '[[ $symbol( $version) ]($style)]($style)'

[python]
symbol = " "
style = "fg:color_bg bg:color_lang"
format = '[[ $symbol( $version) ]($style)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg"
format = '[[  $time ](fg:color_text bg:color_bg)]($style)'

[line_break]
disabled = false

[custom.zvm_visual_arrow_before]
command = 'echo '
when = 'case "$ZVM_MODE" in v|vl) exit 0;; *) exit 1;; esac'
style = 'fg:color_vim_visual'
format = '[$output]($style)'

[custom.zvm_visual]
command = 'echo visual'
when = 'case "$ZVM_MODE" in v|vl) exit 0;; *) exit 1;; esac'
style = 'bg:color_vim_visual fg:color_bg'
format = '[ $output]($style)'

[custom.zvm_visual_arrow_after]
command = 'echo  '
when = 'case "$ZVM_MODE" in v|vl) exit 0;; *) exit 1;; esac'
style = 'fg:color_vim_visual'
format = '[$output]($style) '

[custom.zvm_normal_arrow_before]
command = 'echo '
when = 'case "$ZVM_MODE" in n) exit 0;; *) exit 1;; esac'
style = 'fg:color_vim_normal'
format = '[$output]($style)'

[custom.zvm_normal]
command = 'echo normal'
when = 'case "$ZVM_MODE" in n) exit 0;; *) exit 1;; esac'
style = 'bg:color_vim_normal fg:color_bg'
format = '[ $output]($style)'

[custom.zvm_normal_arrow_after]
command = 'echo  '
when = 'case "$ZVM_MODE" in n) exit 0;; *) exit 1;; esac'
style = 'fg:color_vim_normal'
format = '[$output]($style) '

[custom.zvm_insert_ok_arrow_before]
command = 'echo '
when = '[ "${ZVM_MODE:-}" = "i" ] && [ "${STARSHIP_CMD_STATUS:-0}" -eq 0 ]'
style = 'fg:color_vim_insert'
format = '[$output]($style)'

[custom.zvm_insert_ok]
command = 'echo insert'
when = '[ "${ZVM_MODE:-}" = "i" ] && [ "${STARSHIP_CMD_STATUS:-0}" -eq 0 ]'
style = 'bg:color_vim_insert fg:color_bg'
format = '[ $output]($style)'

[custom.zvm_insert_err]
command = 'echo insert'
when = '[ "${ZVM_MODE:-}" = "i" ] && [ "${STARSHIP_CMD_STATUS:-0}" -ne 0 ]'
style = 'bg:color_os fg:color_text'
format = '[ $output]($style)'

[custom.zvm_insert_ok_arrow_after]
command = 'echo  '
when = '[ "${ZVM_MODE:-}" = "i" ] && [ "${STARSHIP_CMD_STATUS:-0}" -eq 0 ]'
style = 'fg:color_vim_insert'
format = '[$output]($style) '

[character]
success_symbol = "[❯](bold #88c0d0)"
error_symbol = "[❯](bold #bf616a)"
vimcmd_symbol = ""
