[ui]
nav_mode = true
nav_bar = "Plain"
nav_color = "Cyan"

[tui]
percentage = 80
min = 10
max = 100

[preview]
show = true
wrap = true

[preview.border]
title_fg = "Cyan"
color = "Blue"
type = "Rounded"

[[preview.layout]]
command = "if [ -f {1} ]; then cp {1} ~/.config/hypr/animations.conf 2>/dev/null && hyprctl reload >/dev/null 2>&1; bat --paging=never --style=header,grid,numbers --color=always {1} 2>/dev/null || cat {1}; fi"
side = "right"
percentage = 65

[start.command]
separator = "\n"
cmd = "ls -1 $HOME/.config/hypr/animations/*.conf | xargs -n1 basename"

[query]
prompt = " Hyprland Animations > "
prompt_style.fg = "Cyan"

[start]
mode = "nav"
input_separator = "\n"
output_separator = "\n"

[binds]
"ctrl-j" = "Down"
"ctrl-k" = "Up"
"enter" = "Accept"
"esc" = "Quit"
"q" = "Quit"
"nav^^enter" = "Accept"
"nav^^q" = "Quit"
"nav^^esc" = "Quit"
