[ui]
nav_mode = true
nav_bar = "Plain"
nav_color = "Black"

[results]
icons = true
symlink_target = true
symlink_target_style.fg = "cyan"

[preview]
media = true

[preview.border]
title_fg = "cyan"
color = "blue"

[[preview.layout]]
command = "if [ -d {1} ]; then eza --tree --level=2 --icons --color=always {1}; else bat --style=numbers --color=always --line-range=:300 {1}; fi"
side = "right"
percentage = 80