[start]
sort = false
ansi = true
reload_interval = 1800

[matcher]
sort_threshold = false

[columns]
split = '\t'
names = [
    { name = "title", ignore = true },
    { name = "idx" },
    { name = "name" },
    { name = "session" },
    { name = "display", ignore = true }
]

[tui]
mouse = true
percentage = 100
max = 9999

[results]
spinner_prefix = "@SPIN@"
spinner_inline = true
current_prefix = " "
unselected_prefix = ""
row_connection = "Disjoint"
column_spacing = 0

[results.autoscroll]
enabled = false

[results.border]
sides = ""

[query]
status_inline = true
prompt = " "

[ui.border]
sides = ""

[preview]
wrap = false

[preview.border]
sides = "LEFT"
color = "Gray"

[[preview.layout]]
command = 'sess="{=session}"; tmux capture-pane -ep -t "${sess}:{=idx}" 2>/dev/null || printf "  \033[38;2;146;131;116m(no preview)\033[0m\n"'
side = "right"
percentage = 80

[binds]
Start = ["ToggleColumn(title)", "ToggleColumn(name)", "ToggleColumn(session)", "ToggleColumn(idx)"]
