# Global QuiverLink Configuration
# This file contains global settings and shell configuration

# Shell configuration settings
shell:
  shell_type: "zsh"
  config_file: ".zshrc"
  backup_original: true
  global_config: |
    export PATH="$HOME/.local/bin:$PATH"

# Global application settings
app:
  cache_dir: "cache"
  log_level: "info"
  download_timeout_sec: 300
  backup_original_configs: true
  download_mode: "auto"  # Options: "manual", "auto"
  #download_dir: ""       # Empty means use default (~/Downloads for manual)
  #manual_open_browser: true

# Dotfiles configuration
dotfiles:
  base_dir: ".dotfiles"

# Schema version
schema_version: 1
