color_os = "#1b2d40"
color_dir = "#6fa4c9"
color_git = "#5e95bc"
color_lang = "#6fb8e3"
color_vim_insert = "#8bc9eb"
color_vim_normal = "#6fb8e3"
color_vim_visual = "#b4e4f6"
color_comment = "#304860"
