# Fast & Snappy Style
animations {
    enabled = yes
    bezier = ease, 0.25, 0.1, 0.25, 1.0
    bezier = overshot, 0.13, 0.99, 0.29, 1.05
    bezier = liner, 1, 1, 1, 1
    animation = windows, 1, 2, overshot, gnomed
    animation = windowsOut, 1, 2, ease, slide bottom
    animation = windowsMove, 1, 2, overshot, slide
    animation = layers, 1, 2, ease, gnomed
    animation = fade, 1, 1, ease
    animation = border, 1, 1, liner
    animation = borderangle, 1, 180, liner, loop
    animation = workspaces, 1, 2, overshot, slide
}
