# Minimal & Instant Style
animations {
    enabled = yes
    bezier = linear, 0.0, 0.0, 1.0, 1.0
    animation = windows, 1, 1, linear, popin
    animation = windowsOut, 1, 1, linear, popin
    animation = windowsMove, 1, 1, linear
    animation = layers, 1, 1, linear
    animation = fade, 1, 1, linear
    animation = border, 0
    animation = workspaces, 1, 1, linear, fade
}
