git:
  commit:
    generateCommand: "lazycommit commit --message-only --silent-empty"

gui:
  border: "rounded"

keybinding:
  universal:
    refresh: "r"
    quit: "q"
    quit-alt1: "<c-c>"
    return: "<escape>"
  files:
    generateAICommit: "G"
    commitChanges: "C"
  commitMessage:
    commitMenu: "<c-o>"
    aiGenerate: "<c-a>"

aiNotes:
  enabled: true
