git:
  commit:
    generateCommand: "lazycommit commit --message-only --silent-empty"

gui:
  border: "rounded"

keybinding:
  universal:
    refresh: "r"
  files:
    generateAICommit: "G"
    commitChanges: "C"
  commitMessage:
    commitMenu: "<c-o>"
    aiGenerate: "<c-g>"

aiNotes:
  enabled: true
