
color_os = "#0d0d0d"
color_dir = "#cecece"
color_git = "#b6b6b6"
color_lang = "#8d8d8d"
color_vim_insert = "#9b9b9b"
color_vim_normal = "#8d8d8d"
color_vim_visual = "#cecece"
color_comment = "#fdfdfd"

hypr_border_color_1 = "8d8d8dee"
hypr_border_color_2 = "b0b0b0ee"
